service: lambda-helloWorld
package:
  individually: true
frameworkVersion: "2"
configValidationMode: error
plugins:
    - serverless-offline
custom:
  bundle:
    linting: false
provider:
    name: aws
    runtime: nodejs14.x
    lambdaHashingVersion: "20201221"
    profile: serverless-profile
functions:
    lambda-helloWorld:
        handler: app.handler
        events:
            - httpApi:
                path: /{proxy+}
                method: '*'